사격장 인벤토리 만들기
MineFactory-Resource/ShootingTest pull request #1
Opened 2022-09-21 06:39 UTC by Seokhun-Yang

2022-09-23 07:16 UTC, Fade-Jung approved these changes

2022-09-23 18:15 UTC, LesserJang requested changes

2022-09-23 18:15 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/config/ItemManager.java
> +        }
이름과 로어같은 아이템설정도 있어야할 것 같아요

2022-09-23 18:15 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/events/playerTeleport.java
> +public class PlayerTeleport implements Listener {
클래스 이름이랑 파일명이 달라요

2022-09-23 18:15 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/config/ItemManager.java
> +    private static FileConfiguration itemsFile;
static 선언 없이 인스턴스 변수로 설정하는게 좋을 것 같아요. static 선언은 무조건 최소한으로 하는게 좋습니다.

2022-09-23 18:15 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/config/MessageManager.java
> +    private static FileConfiguration messagesFile;
마찬가지로 static 선언 없이 해주시는게 좋을 것 같아요

2022-09-24 01:28 UTC, tjrhuni commented on src/main/java/net/teamuni/shootingtest/events/playerTeleport.java
> +public class PlayerTeleport implements Listener {
이상하네요... 제 로컬 브랜치에서는 클래스명이랑 파일명이 같은데.. 커밋을 하려고 해도 커밋할 것이 없다고 떠요

2022-09-24 01:30 UTC, tjrhuni commented on src/main/java/net/teamuni/shootingtest/config/ItemManager.java
> +        }
이 브랜치는 사격장의 인벤토리만 구현하는 것이라서, 다음 브랜치에서 이름과 로어를 설정할 수 있도록 하는 기능을 추가하고 ItemMeta를 사용하여 아이템 구분을 하였습니다.

2022-09-24 01:30 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shootingtest/config/ItemManager.java
> +    private static FileConfiguration itemsFile;
넵 수정하도록 하겠습니다

2022-09-24 01:31 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shootingtest/events/playerTeleport.java
> +public class PlayerTeleport implements Listener {
![image](https://user-images.githubusercontent.com/95516455/192074502-7c05d70f-e8f6-4b2a-90be-4da0a52aed43.png)

2022-09-24 08:35 UTC, LesserJang requested changes

2022-09-24 08:35 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/ShootingTest.java
> +    public MessageManager messageManager;
private final로 선언해서 변수 보호해주세요. 솔직히 그럴 가능성은 전혀 없긴한데 외부에서 마음대로 저 매니저 변수를 바꿔치기 할 수도 있는 그런 보안 문제가 있어요.

2022-09-24 08:35 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/ShootingTestInv.java
> +        ItemManager itemManager = main.itemManager;
lombok으로 Getter를 선언하셨으면 getter를 사용해주세요

2022-09-24 08:35 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/command/ShootingTestCmd.java
> +    private final MessageManager messageManager = main.messageManager;
getInstance로 가져오지 마시고 생성자에서 ShootingTest 객체를 파라미터로 받아와서 사용하는게 더 좋을 것 같아요. 또, ShootingTest 객체만 변수로 저장해두시고 Manager 클래스들은 그때그때 main.getItemManger() 로 불러오는게 더 좋아요.

2022-09-24 08:35 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/events/PlayerTeleport.java
> +    private final ShootingTest main = ShootingTest.getInstance();
이것도 생성자에서 ShootingTest 객체 받아오는게 getInstance보다 좋아요.

2022-09-24 09:04 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shootingtest/command/ShootingTestCmd.java
> +    private final MessageManager messageManager = main.messageManager;
혹시 getInstance()로 가져오는 것보다 생성자에서 객체를 parameter로 받아와서 사용하는게 더 좋은 이유랑 Manager 클래스들은 그때그때  main.getItemManger()와 같이 불러오는 게 더 좋은 이유를 알려주실 수 있으실까요? 궁금합니다.. 혹시 유지보수 때문일까요? 아니면 가독성?

2022-09-24 09:15 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/command/ShootingTestCmd.java
> +    private final MessageManager messageManager = main.messageManager;
static 메소드로 객체 가져오는 것과 생성될 때 파라미터로 받아오는건 속도 차이가 있긴해요. 또, 그때그때 불러오는 이유는 ShootingTest 클래스에서 ItemManager 객체를 바꿔도 해당 클래스에서는 그 바뀐 객체를 가져오지 않기 때문이에요. 사실 구조상 이렇게 써도 되긴하지만, 나중에 문제가 생길 것 같기도 하고 제가 이 코드를 봤을 때 뭔가 불편함이 느껴져서 말했어요. 약간 바뀌지 않는 상수값을 final 선언 안한것같은 느낌?..

2022-09-24 09:16 UTC, LesserJang requested changes

2022-09-24 09:16 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/ShootingTest.java
> +    }
이미 @Getter 선언 하셔서 메소드 선언 따로 안하셔도 됩니다

2022-09-24 09:17 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shootingtest/ShootingTest.java
> +    }
아차차.. 집에 도착하면 바로 수정하도록 하겠습니다!!

2022-09-24 09:17 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shootingtest/command/ShootingTestCmd.java
> +    private final MessageManager messageManager = main.messageManager;
아하 설명해주셔서 감사합니다!

2022-09-24 09:59 UTC, LesserJang commented
GunsCore랑 같이 사용했을때 로비아이템쪽에서 문제 생길수도 있을것같은데 테스트 해보셨나요?

2022-09-24 10:00 UTC, Seokhun-Yang commented
테스트 해보았는데 아이템은 정상적으로 바뀌나 기능이 GunsCore 로비 아이템 기능대로 작동을 해서.. PR 2번에서 수정할 생각입니다.

2022-09-24 10:17 UTC, LesserJang approved these changes

2022-09-26 10:39 UTC, merged