무기 메뉴에서 스킨이 적용되어 총이 보이지 않는 문제 해결하기
MineFactory-Resource/ShootingTest pull request #11
Opened 2022-12-21 09:11 UTC by Seokhun-Yang

2022-12-25 10:27 UTC, kari0707 approved these changes

2022-12-26 10:28 UTC, LesserJang requested changes

2022-12-26 10:28 UTC, LesserJang commented on src/main/java/net/teamuni/shootingtest/config/StInventory.java
> +public class StInventory implements Listener {
클래스 이름은 왠만하면 명사로 시작해서 명확하게 이게 어떤 클래스인지 또는 어떤기능과 관련있는 클래스인지 알 수 있어야 합니다.

2022-12-26 10:44 UTC, LesserJang approved these changes

2022-12-26 10:45 UTC, merged